x-dds-configs:
  - &client_config { network_mode: host, ipc: host, configs: [ client.xml ], env_file: dds/client.env }
  - &server_config { network_mode: host, ipc: host, configs: [ server.xml ], env_file: dds/server.env }
  - &simple_config { network_mode: host, ipc: host, configs: [ simple.xml ], env_file: dds/simple.env }

configs: 
  client.xml: { file: dds/client.xml }
  server.xml: { file: dds/server.xml }
  simple.xml: { file: dds/simple.xml }

services:

  rviz:
    <<: *client_config
    image: husarion/rviz2:humble
    container_name: rviz
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rbxl.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
