# ================ DDS configs ================ #

x-vpn-config:
  - &client_config
    network_mode: host
    ipc: host
    configs: [ client.xml ]
    env_file: dds/client.env

  - &server_config
    network_mode: host
    ipc: host
    configs: [ server.xml ]
    env_file: dds/server.env
    
  - &simple_config
    network_mode: host
    ipc: host
    configs: [ simple.xml ]
    env_file: dds/simple.env

configs:
  client.xml: { file: dds/client.xml }
  server.xml: { file: dds/server.xml }
  simple.xml: { file: dds/simple.xml }

# ================= services ================== #

services:

  discovery-server:
    <<: *server_config
    image: ros:humble-ros-core
    command: fast-discovery-server -x /server.xml

  rosbot-xl:
    <<: *client_config
    image: husarion/rosbot-xl:humble
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-False}

  rplidar:
    <<: *client_config
    image: husarion/rplidar:humble
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    command: >
      ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-115200}

  microros:
    <<: *client_config
    image: microros/micro-ros-agent:humble
    volumes:
      - ./micro-ros_entrypoint.sh:/micro-ros_entrypoint.sh
    command: udp4 --port 8888
